vim.keymap.set({ 'i' }, 'jk', '<ESC>')
vim.keymap.set({ 'v' }, '<leader>c', '"+y')
vim.keymap.set({ 'n' }, '<leader>w', ':set wrap!<CR>')
vim.keymap.set({ 'n' }, '<leader>n', ':set rnu!<CR>')
vim.keymap.set({ 'n' }, '<leader>es', ':! eslint_d --fix %<CR><CR>')
